//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:/workspace/antlr_formula\Formula.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
internal partial class FormulaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, NumeralLiteral=11, Identifier=12, MethodOrPropertyIdentity=13, 
		WS=14;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "NumeralLiteral", "Identifier", "MethodOrPropertyIdentity", "Letter", 
		"LetterOrDigit", "DecimalNumeral", "FloatingPointNumeral", "Digits", "Digit", 
		"NonZeroDigit", "Sign", "WS"
	};


	public FormulaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public FormulaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'*'", "'/'", "'+'", "'-'", "','", "'${'", "'}'", 
		"'%'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "NumeralLiteral", 
		"Identifier", "MethodOrPropertyIdentity", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Formula.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static FormulaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x10', 'z', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x5', '\f', 'G', '\n', '\f', '\x3', '\r', '\x3', '\r', '\a', '\r', 'K', 
		'\n', '\r', '\f', '\r', '\xE', '\r', 'N', '\v', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x5', 
		'\xF', 'V', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', 
		'Z', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', 
		'\x11', '_', '\n', '\x11', '\x5', '\x11', '\x61', '\n', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x6', 
		'\x13', 'h', '\n', '\x13', '\r', '\x13', '\xE', '\x13', 'i', '\x3', '\x14', 
		'\x3', '\x14', '\x5', '\x14', 'n', '\n', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x6', '\x17', 'u', 
		'\n', '\x17', '\r', '\x17', '\xE', '\x17', 'v', '\x3', '\x17', '\x3', 
		'\x17', '\x2', '\x2', '\x18', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x2', '\x1F', '\x2', '!', '\x2', '#', '\x2', '%', '\x2', '\'', '\x2', 
		')', '\x2', '+', '\x2', '-', '\x10', '\x3', '\x2', '\b', '\x6', '\x2', 
		'&', '&', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x4', '\x2', '\x2', 
		'\x81', '\xD802', '\xDC01', '\a', '\x2', '&', '&', '\x32', ';', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', '\x33', ';', '\x4', '\x2', 
		'-', '-', '/', '/', '\x5', '\x2', '\v', '\f', '\xE', '\xF', '\"', '\"', 
		'\x2', 'z', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '/', '\x3', '\x2', '\x2', '\x2', '\x5', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\a', '\x33', '\x3', '\x2', '\x2', '\x2', '\t', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\v', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\r', '\x39', '\x3', '\x2', '\x2', '\x2', '\xF', ';', '\x3', '\x2', '\x2', 
		'\x2', '\x11', '=', '\x3', '\x2', '\x2', '\x2', '\x13', '@', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\x42', '\x3', '\x2', '\x2', '\x2', '\x17', '\x46', 
		'\x3', '\x2', '\x2', '\x2', '\x19', 'H', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'O', '\x3', '\x2', '\x2', '\x2', '\x1D', 'U', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', 'Y', '\x3', '\x2', '\x2', '\x2', '!', '`', '\x3', '\x2', '\x2', 
		'\x2', '#', '\x62', '\x3', '\x2', '\x2', '\x2', '%', 'g', '\x3', '\x2', 
		'\x2', '\x2', '\'', 'm', '\x3', '\x2', '\x2', '\x2', ')', 'o', '\x3', 
		'\x2', '\x2', '\x2', '+', 'q', '\x3', '\x2', '\x2', '\x2', '-', 't', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x30', '\a', '*', '\x2', '\x2', '\x30', '\x4', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\a', '+', '\x2', '\x2', '\x32', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\a', ',', '\x2', '\x2', 
		'\x34', '\b', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', '\x31', 
		'\x2', '\x2', '\x36', '\n', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', 
		'\a', '-', '\x2', '\x2', '\x38', '\f', '\x3', '\x2', '\x2', '\x2', '\x39', 
		':', '\a', '/', '\x2', '\x2', ':', '\xE', '\x3', '\x2', '\x2', '\x2', 
		';', '<', '\a', '.', '\x2', '\x2', '<', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'=', '>', '\a', '&', '\x2', '\x2', '>', '?', '\a', '}', '\x2', '\x2', 
		'?', '\x12', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\a', '\x7F', '\x2', 
		'\x2', '\x41', '\x14', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\a', 
		'\'', '\x2', '\x2', '\x43', '\x16', '\x3', '\x2', '\x2', '\x2', '\x44', 
		'G', '\x5', '!', '\x11', '\x2', '\x45', 'G', '\x5', '#', '\x12', '\x2', 
		'\x46', '\x44', '\x3', '\x2', '\x2', '\x2', '\x46', '\x45', '\x3', '\x2', 
		'\x2', '\x2', 'G', '\x18', '\x3', '\x2', '\x2', '\x2', 'H', 'L', '\x5', 
		'\x1D', '\xF', '\x2', 'I', 'K', '\x5', '\x1F', '\x10', '\x2', 'J', 'I', 
		'\x3', '\x2', '\x2', '\x2', 'K', 'N', '\x3', '\x2', '\x2', '\x2', 'L', 
		'J', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\x3', '\x2', '\x2', '\x2', 
		'M', '\x1A', '\x3', '\x2', '\x2', '\x2', 'N', 'L', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'P', '\x5', '\x19', '\r', '\x2', 'P', 'Q', '\a', '\x30', '\x2', 
		'\x2', 'Q', 'R', '\x5', '\x19', '\r', '\x2', 'R', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'V', '\t', '\x2', '\x2', '\x2', 'T', 'V', '\n', '\x3', 
		'\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'V', '\x1E', '\x3', '\x2', '\x2', '\x2', 'W', 'Z', '\t', 
		'\x4', '\x2', '\x2', 'X', 'Z', '\n', '\x3', '\x2', '\x2', 'Y', 'W', '\x3', 
		'\x2', '\x2', '\x2', 'Y', 'X', '\x3', '\x2', '\x2', '\x2', 'Z', ' ', '\x3', 
		'\x2', '\x2', '\x2', '[', '\x61', '\a', '\x32', '\x2', '\x2', '\\', '^', 
		'\x5', ')', '\x15', '\x2', ']', '_', '\x5', '%', '\x13', '\x2', '^', ']', 
		'\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', '\x2', '\x2', '_', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '`', '[', '\x3', '\x2', '\x2', '\x2', 
		'`', '\\', '\x3', '\x2', '\x2', '\x2', '\x61', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x63', '\x5', '%', '\x13', '\x2', '\x63', '\x64', '\a', 
		'\x30', '\x2', '\x2', '\x64', '\x65', '\x5', '%', '\x13', '\x2', '\x65', 
		'$', '\x3', '\x2', '\x2', '\x2', '\x66', 'h', '\x5', '\'', '\x14', '\x2', 
		'g', '\x66', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'g', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\x3', '\x2', '\x2', 
		'\x2', 'j', '&', '\x3', '\x2', '\x2', '\x2', 'k', 'n', '\a', '\x32', '\x2', 
		'\x2', 'l', 'n', '\x5', ')', '\x15', '\x2', 'm', 'k', '\x3', '\x2', '\x2', 
		'\x2', 'm', 'l', '\x3', '\x2', '\x2', '\x2', 'n', '(', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'p', '\t', '\x5', '\x2', '\x2', 'p', '*', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\t', '\x6', '\x2', '\x2', 'r', ',', '\x3', '\x2', '\x2', 
		'\x2', 's', 'u', '\t', '\a', '\x2', '\x2', 't', 's', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'v', '\x3', '\x2', '\x2', '\x2', 'v', 't', '\x3', '\x2', '\x2', 
		'\x2', 'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', '\x2', '\x2', 
		'\x2', 'x', 'y', '\b', '\x17', '\x2', '\x2', 'y', '.', '\x3', '\x2', '\x2', 
		'\x2', '\f', '\x2', '\x46', 'L', 'U', 'Y', '^', '`', 'i', 'm', 'v', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
